### ISSUE TITLE
Manually set parameters as required

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#117]
For POWERBIDEDICATED, there is a parameter which should be required for the resource, but doesn't show up as required.

parameter name: administration-members
swagger definition: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2017-10-01/powerbidedicated.json#L778

Server side error "At least one capacity administrator is required".

From the swagger definition, it may be hard to find such required parameter. But is there a way to set some parameter as required in readme?

**Comment by RodgeFu** [comment]
the directive support in clicommon is ready. people can add the required property easily by using directive. @qiaozhao, do we need any change in autorest.az to support it when generating code?

**Comment by qiaozha** [comment]
> the directive support in clicommon is ready. people can add the required property easily by using directive. @Qiaozhao, do we need any change in autorest.az to support it when generating code?

I think we probably still need to separate cli common modifiers into independent plugin so that az and terraform can set their own directive. 
Since we've already can make python/namer take cli.common's  output as input. I think they can be separated into multi-plugins now. will have to check on that.

**Comment by RodgeFu** [comment]
the directive config of clicommon is not necessary in clicommon's config. you can put clicommon directive in readme.az.md, the same for terraform to add in readme.terraform.md. like i set modelerfour's config in clicommon's readme.

about separating to multiple plugin, yes, i think we can have a refactor for it. will create an issue to track it. thx

**Comment by qiaozha** [comment]
I see, then I think it’s  enough to support manually set required parameters for now

**Comment by qiaozha** [comment]
Hi  @Juliehzl  This can be support in az now. You can configure it this way https://github.com/Azure/autorest.az/blob/290f4326058892cb90725f672a4bfda73590607f/src/test/scenarios/managed-network/configuration/readme.az.md#L49-L51 
if you want to specify which operationGroup which operation. you can also put it in the where clause.
