### ISSUE TITLE
Wrong examples

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#118]
The generated examples description are wrong in some cases.
For example,
```
      - name: Get details of a capacity
        text: |-
               az powerbi embedded-capacity delete --resource-group "TestRG" --name "azsdktest"

      - name: Get details of a capacity
        text: |-
               az powerbi embedded-capacity list

```
The first command is for delete and the second one is for list.

**Comment by changlong-liu** [comment]
Have just implemented this example generation in _help.py.
And the example descriptions in _help.py are come from the swagger example, if it's wrong it should be a mistake in swagger example.
