### ISSUE TITLE
CLI should accept either resource name or resource ARM ID using the same parameter

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#147]
CLI should accept either resource name or resource ARM ID using the same parameter.
You can refer to https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#supporting-name-or-id-parameters

**Implementation logic likes as follows:**
```
if not is_valid_resource_id(namespace.managed_resource_group):
      namespace.managed_resource_group = resource_id(
            subscription=get_subscription_id(cmd.cli_ctx),
            resource_group=namespace.managed_resource_group)
```

**CLI commands usages for users:**
- az databricks workspace create --managed_resource_group my-rg
- az databricks workspace create --managed_resource_group "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09592/resourceGroups/my-rg/"

**Comment by LianwMS** [comment]
Fixed
