### ISSUE TITLE
Issue of auto genereted DataFactory code

### ISSUE THREAD

**Issue by arrownj** [Azure/autorest.az#15]
1. syntax error for if-none-match in python code
2. _params.py import azext_datafactory.action, however there is no action.py generated
3. get_three_state_flag function not import from azure.cli.core.commands.parameters
4. No body variable in some custom functions
5. json module not import
6. Add vendored_sdks manually
7. az datafactory create, --git-hub-access-code, --git-hub-access-token-base-url is required which are not mandatory in portal and PowerShell

**Comment by RodgeFu** [comment]
please separate the big issues to smaller ones so that it's easier to track and label, thanks.

**Comment by RodgeFu** [comment]
zim, please help to split the issue into smaller ones and we can triage next time on the sub items.

**Comment by RodgeFu** [comment]
separated issues are created to track each item
