### ISSUE TITLE
Some parameters of self-defined type  are not generated properly

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#18]
These are not generated properly, could be related to flatten:
1. name: [parameters](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/notificationhubs.json#L87), type:CheckAvailabilityParameters used in [check_availability_notificationhubs_namespace](https://github.com/Azure/azure-cli-extensions/pull/1143/files#diff-70f1bd7dba75d5c4487be97cdedb1436R99),  generated code is using `body = {}` inside the function and does not pass the parameters in. Similarly, name:[parameters](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/notificationhubs.json#L1079), type:SharedAccessAuthorizationRuleCreateOrUpdateParameters used in [create_or_update_authorization_rule_notificationhubs_namespace](https://github.com/Azure/azure-cli-extensions/pull/1143/files#diff-70f1bd7dba75d5c4487be97cdedb1436R132)), generated code is using `body = {}` inside the function and does not pass the parameters in.

2. [NotificationHubProperties](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/notificationhubs.json#L2075...L2118) of [NotificationHubCreateOrUpdateParameters](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/notificationhubs.json#L2119..L2136) used in [create_notificationhubs_hub](https://github.com/Azure/azure-cli-extensions/blob/202fc1aae70d157039958e20dfc8e972686ba8dc/src/notificationhubs/azext_notificationhubs/custom.py#L151..L160) is lost. Similary NamespaceProperties of NamespaceCreateOrUpdateParameters in create_notificationhubs_namespace is also lost.

**Comment by zikalino** [comment]
this issue is fixed
