### ISSUE TITLE
Use name_type

### ISSUE THREAD

**Issue by jiasli** [Azure/autorest.az#204]
Same as https://github.com/Azure/autorest.az/issues/64

`name_type` should be imported from `azure.cli.core.commands.parameters` and used for `name` parameters:

```py
c.argument('name', arg_type=name_type, help='The name of the Time Series Insights environment.')
```

**Comment by LianwMS** [comment]
We have fixed it by add the option-list. The reason that we not use name_type is to support more alias which can be defined in directive
