### ISSUE TITLE
example of '--properties-metadata' not correct

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.az#210]
![image](https://user-images.githubusercontent.com/6038235/76686419-29a32600-6656-11ea-8d30-eb2249f6e517.png)

**Comment by changlong-liu** [comment]
![image](https://user-images.githubusercontent.com/59815250/76723435-3cb31480-6782-11ea-87c9-29ae09d99fb1.png)


The '--properties-meta' is a property which has type "any", will transfer "metadata" to JSONstring in this kind of case.

**Comment by changlong-liu** [comment]
![image](https://user-images.githubusercontent.com/59815250/76819719-063dce00-6844-11ea-8cc6-231c43e35d55.png)

swagger definition of this property.
