### ISSUE TITLE
Python SDK removed wrapper when it only has 1 property, but CLI code doesn't

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#22]
The example of NameSpaceAuthorizationRuleCreate is [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/examples/Namespaces/NHNameSpaceAuthorizationRuleCreate.json). You can see [`properties`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/examples/Namespaces/NHNameSpaceAuthorizationRuleCreate.json#L10) is wrapped by [`parameters`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/examples/Namespaces/NHNameSpaceAuthorizationRuleCreate.json#L9).

In generated python sdk code, the wrapper `parameters` is thrown away because it only has one property called `properties`, so it uses `properties` directly [here](https://github.com/Azure/azure-cli-extensions/blob/202fc1aae70d157039958e20dfc8e972686ba8dc/src/notificationhubs/azext_notificationhubs/vendored_sdks/notificationhubs/operations/namespaces_operations.py#L393). 

The generated CLI code does not have this behavior and still passes `parameters` to python sdk [here](https://github.com/Azure/azure-cli-extensions/blob/202fc1aae70d157039958e20dfc8e972686ba8dc/src/notificationhubs/azext_notificationhubs/custom.py#L137). This caused an exception.

**Comment by zikalino** [comment]
should be fixed in  0.1.866

**Comment by RodgeFu** [comment]
fixed. please verify
