### ISSUE TITLE
About example, prefer one line. Here is the sample generated by Aladdin.

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.az#230]
Prefer one line. Here is the sample generated by Aladdin.
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fpull%2F12495%2Ffiles%23diff-bad2286473bc70c5bd544988ef5fdc65R1147&data=02%7C01%7Cwenjiefu%40microsoft.com%7C47c1fc82107c49d6cca308d7ccb19e89%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637202935558120241&sdata=dnqjcj0x00FpvpVPT5kiTJakCBWpWXjkFPlRk%2Ftd9zE%3D&reserved=0

**Comment by yonzhan** [comment]
Yes, Aladdin prefers one line:)
