### ISSUE TITLE
support etag in our operation

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.az#241]
'az costmanagement export update ...' requires etag

link to the team discussion: https://teams.microsoft.com/l/message/19:2ce4b07e919c4018baf2826f821596ec@thread.skype/1585017299974?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de995b1a-16c1-4cc7-a49b-bc9f90bc6acd&parentMessageId=1584976719596&teamName=Azure%20Management%20Experience&channelName=Azure%20CLI&createdTime=1585017299974 

![image](https://user-images.githubusercontent.com/6038235/77382853-668cbc80-6dbc-11ea-81ad-3ed7795a60f9.png)

**Comment by zikalino** [comment]
another issue #374
