### ISSUE TITLE
Should import from the combined commands and _params instead of only generated ones

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#257]
Generated code in `azext_xxx/__init__.py`:

> from .generated.commands import load_command_table
> from .generated._params import load_arguments

Recommended code:

> from .commands import load_command_table
> from ._params import load_arguments

A combined `_params.py` is not provided now. Please add it along with `_help.py`.

**Comment by fengzhou-msft** [comment]
@RodgeFu I marked this issue as blocking as I saw the two new PRs(https://github.com/Azure/azure-cli-extensions/pull/1428, https://github.com/Azure/azure-cli-extensions/pull/1423) are both modifying generated code instead of adding manual code. Please resolve this ASAP so we can follow the approach to use the `manual` folder.

Maybe you can generate an empty `manual` folder so people are better aware of this feature.

**Comment by RodgeFu** [comment]
it's already supported in latest code, but just not released yet. I will send out a private release today or tomorrow including the manual override. thanks.

**Comment by zikalino** [comment]
as it's resolved already, I am closing
