### ISSUE TITLE
Don't always replace resource name with random name in test.

### ISSUE THREAD

**Issue by zikalino** [Azure/autorest.az#270]
I just encountered following:
            'myJob': self.create_random_name(prefix='cli_test_jobs'[:9], length=24),
and replaced it with:
            'myJob': "myJob",

Sometimes fixed name coming with the example is sufficient.
Usually randmization is needed when API provides "check_name_availability" method.

In case above i encountered error because random name was not meeting job name criteria.

**Comment by zikalino** [comment]
Another solution:
"myJob" -> "myJob{unique}"

**Comment by changlong-liu** [comment]
in latest PR, the randomize name is set as to have the same length with example name：
“myManagedNetwork" -> ”myManagxxxxxxxxx“
