### ISSUE TITLE
blueprint assignment commands naming issue

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#28]
The generated code has two command groups named `blueprint`. The [second group](https://github.com/Azure/azure-cli-extensions/pull/1164/commits/017d5e7d8cd9cc47dacce230413338232bd3ad6b#diff-2b539f959ab6566bc06b0cfb29cf9ae8R60) may well be named `blueprint assignment`. It also has two groups of different methods with the same name such as `create_blueprint`, `update_blueprint` in `custom.py`.

**Comment by zikalino** [comment]
I think this shouldn't happen with my recent updates to default command namer

**Comment by RodgeFu** [comment]
please verify
