### ISSUE TITLE
Support command interface changes to remove or add a subgroup in readme configuration

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#297]
For datashare, we would like to make the following changes in the command names:
Remove subgroup: 
datashare share -> datashare
Add subgroup:
datashare trigger -> datashare consumer trigger
datashare share-subscription -> datashare consumer share-subscription
datashare data-set-mapping -> datashare consumer dataset-mapping
datashare consumer-invitation -> datashare consumer invitation
datashare consumer-source-data-set ->  datashare consumer source-dataset

Please add support for it in the readme configuration. Other services may have similar requests.

**Comment by yonzhan** [comment]
This is a good requirement.

**Comment by zikalino** [comment]
this is already done
