### ISSUE TITLE
Azure CLI, remove example code in _validators.py

### ISSUE THREAD

**Issue by qwordy** [Azure/autorest.az#306]
Can we remove `def example_name_or_id_validator(cmd, namespace)` in _validator.py?
The motivation of providing this function is good. But it is useless in real world.

**Comment by qwordy** [comment]
Why close the issue without any comment? T_T

**Comment by qiaozha** [comment]
This should have been fixed in the latest autorest.az master code.

**Comment by qwordy** [comment]
OK. Thank you!
