### ISSUE TITLE
use hyphen for all command name

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#32]
Some generated command name uses underline, such as [`regenerate_keys`](https://github.com/Azure/azure-cli-extensions/pull/1143/commits/cf0bcf42667b91c1bd27abfbdce803bcba3bcca7#diff-d84bf1399ce60ee3f860a9d18d9a0a11R34). According to [command guideline](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#command-naming-and-behavior), we should use hyphen.

**Comment by zikalino** [comment]
fixed in  0.1.866

**Comment by fengzhou-msft** [comment]
verified.
