### ISSUE TITLE
support --ids

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.az#339]
https://github.com/Azure/azure-cli-extensions/pull/1428#issuecomment-618770557

**Comment by fengzhou-msft** [comment]
Just to clarify, `--ids` is not needed for create/list commands, it's needed for update/show/delete commands and potentially other commands that is targeting the operations on a single existing main resource of the command. 

We can start with supporting configuring `id_part` in readme, which should be quick to add. Adding it automatically in generated code may be complicated. You can make use of the [parse_resource_id](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/tools.py#L106) method in msrestazure if possible. All the available `id_part` is commented [here](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/tools.py#L115-L129).
