### ISSUE TITLE
override on parameter name $filter results to two parameters

### ISSUE THREAD

**Issue by changlong-liu** [Azure/autorest.az#379]
After add below directive in readme:
![image](https://user-images.githubusercontent.com/59815250/82773741-615bf480-9e75-11ea-86a9-a06e4773b6a2.png)

Both original name "filter" and new name "list-filter" become a parameter in _params.py and custom.py:
![image](https://user-images.githubusercontent.com/59815250/82773822-9700dd80-9e75-11ea-8582-d21f8e57b36a.png)

**Comment by LianwMS** [comment]
Merged and Close
