### ISSUE TITLE
"azext.maxCliCoreVersion": "2.1.0" in azext_metatdata.json

### ISSUE THREAD

**Issue by MyronFanQiu** [Azure/autorest.az#41]
Since we plan to use new version information here. It's better to set the default maxCliCoreVersion to 3.0.0. if we can set this in readme.cli.md, that's would be more flexible. 
**This is not urgent.**

**Comment by zikalino** [comment]
just changed it to 3.0.0, I think it shouldn't be configurable right now, but rather should change with releases of codegen
