### ISSUE TITLE
Support version customization in manual folder

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#417]
CLI developers can set version in manual folder to overwrite the version in generated folder so the CLI extension can be released with correct version.

**Comment by RodgeFu** [comment]
should have supported, needs double verify.

**Comment by qiaozha** [comment]
Please use the latest private release and regenerate the code. Then follow the guideline here. https://github.com/Azure/autorest.az/blob/master/doc/03-manual-customizations.md#overriding-version

**Comment by LianwMS** [comment]
Merged and Closed
