### ISSUE TITLE
Use Python auto-format plugin to help format generated CLI code such as black, pep8 and etc

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#418]
CodeGen can use Python auto-format plugin to help format generated CLI code such as black, pep8 and etc so that the generated CLI code is more readable.

**Comment by RodgeFu** [comment]
the word breaking issue has been fixed. Put this in backlog for using auto-format plugin until it's really needed because the cost is not low.

**Comment by changlong-liu** [comment]
supported with python solution
