### ISSUE TITLE
[Style check failure] Too many blank lines

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#426]
![image](https://user-images.githubusercontent.com/16348853/84857895-a5b96980-b09c-11ea-961c-63dbc3904e12.png)

![image](https://user-images.githubusercontent.com/16348853/84857832-7a367f00-b09c-11ea-8ba6-411f3bd514d6.png)

**Comment by RodgeFu** [comment]
please verify it in the latest private bit: https://github.com/Azure/autorest.az/releases/tag/1.4.1-b.20200622.1

**Comment by LianwMS** [comment]
Merged and closed
