### ISSUE TITLE
[Style check failure] Unexpected spaces around keyword

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#427]
![image](https://user-images.githubusercontent.com/16348853/84858093-0f397800-b09d-11ea-8702-08fab6ab56d2.png)

![image](https://user-images.githubusercontent.com/16348853/84858122-1fe9ee00-b09d-11ea-834b-6881a82195ec.png)

**Comment by RodgeFu** [comment]
please verify it in private release: https://github.com/Azure/autorest.az/releases/tag/1.4.1-b.20200622.1
