### ISSUE TITLE
[Style check failure] Unused argument

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#430]
![image](https://user-images.githubusercontent.com/16348853/84859781-668d1780-b0a0-11ea-8d0e-daed6f3d418f.png)

![image](https://user-images.githubusercontent.com/16348853/84859836-815f8c00-b0a0-11ea-9e61-d34f09bf3cba.png)

**Comment by qiaozha** [comment]
For generic update. there indeed will be argument used for get operation and will not be used in the custom function. We have add pylint disable logic in the latest codegen private release. The other part should have been fixed

**Comment by LianwMS** [comment]
Fix and Closed
