### ISSUE TITLE
[CLI guideline] Function name should use underscore instead of double understore

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#433]
![image](https://user-images.githubusercontent.com/16348853/84867928-7ad81100-b0ae-11ea-9f59-1e64e14d5468.png)

**Comment by RodgeFu** [comment]
let's double check the unexpected double _

**Comment by qiaozha** [comment]
@jsntcy  This is because the operationId doesn't have underscore separate it. causing the the modelerfour fail the recognize the operationGroupName. Do you think this is a common case in swagger? I am not sure whether we should fix it from codegen side or from swagger side?

**Comment by qiaozha** [comment]
Just check with swagger team. This is an invalid operationId https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r2055

**Comment by LianwMS** [comment]
swagger should follow the rule
