### ISSUE TITLE
[Style check failure]  Unnecessary "else" after "return" (no-else-return)

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#434]
![image](https://user-images.githubusercontent.com/16348853/84869243-5c731500-b0b0-11ea-94d4-71d2ab7182f4.png)

![image](https://user-images.githubusercontent.com/16348853/84869332-790f4d00-b0b0-11ea-9614-34d7e425348c.png)

**Comment by LianwMS** [comment]
Merged and close
