### ISSUE TITLE
[Style check failure] Disable too-many-locals, too-many-statements for commands.py

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#436]
![image](https://user-images.githubusercontent.com/16348853/84871335-f9cf4880-b0b2-11ea-8dde-d8fb3e082629.png)

![image](https://user-images.githubusercontent.com/16348853/84871359-0358b080-b0b3-11ea-8da2-0c8f26d984f9.png)

**Comment by RodgeFu** [comment]
@jsntcy , this should have been fixed in the latest code. Could you try the latest private release and see whether it still exists? thanks. 
https://github.com/Azure/autorest.az/releases/tag/1.4.1-b.20200622.1
