### ISSUE TITLE
Duplicated option listed in the help text

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.az#441]
Duplicated options in the help text of --identity-type: 
![image](https://user-images.githubusercontent.com/6038235/84978937-c4813400-b160-11ea-8aec-5c8f9f3de774.png)

**Comment by changlong-liu** [comment]
looks like a CLI issue about how to process enum value containing comma.

The generated code is like this:
~~~
        c.argument('identity_type', arg_type=get_enum_type(['SystemAssigned', 'UserAssigned', 'SystemAssigned, '
                   'UserAssigned', 'None']), help='The identity type. Swagger name=type')
~~~
which can match thw swagger definition:
~~~
        "type": {
          "description": "The identity type.",
          "enum": [
            "SystemAssigned",
            "UserAssigned",
            "SystemAssigned, UserAssigned",
            "None"
          ],
          "type": "string",
          "x-ms-enum": {
            "name": "ResourceIdentityType",
            "modelAsString": false
          }
        },
~~~

**Comment by RodgeFu** [comment]
you mean modelerfour issue?

**Comment by changlong-liu** [comment]
I think not a modelerfour issue.  I think it's about how CLI display the enum values, especially when there is some special characters in the enum value, for example the comma in this case.

The enum values defined in this swagger is a little bit unnormal:
~~~
          "enum": [
            "SystemAssigned",
            "UserAssigned",
            "SystemAssigned, UserAssigned",      // unnormal value item
            "None"
          ],
~~~

So logically the "arg_type=get_enum_type(..)" behavior for this enum is correct:
~~~
Allowed values: SystemAssigned, UserAssigned, SystemAssigned, UserAssigned, None
~~~

A solution maybe add some annotations in the result:
~~~
Allowed values: "SystemAssigned", "UserAssigned", "SystemAssigned, UserAssigned", "None"
~~~
the format here is controlled by azure-cli.core

**Comment by RodgeFu** [comment]
Do you know what the "SystemAssigned, User Assigned" mean?

**Comment by changlong-liu** [comment]
Synced with Yugang, "SystemAssigned, User Assigned" means "both SystemAssigned and User Assigned", and several other RPs use  this kind of Enum also.

And I discussed with CLI team here: https://teams.microsoft.com/l/message/19:2ce4b07e919c4018baf2826f821596ec@thread.skype/1593404934668?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de995b1a-16c1-4cc7-a49b-bc9f90bc6acd&parentMessageId=1593404934668&teamName=Azure%20Management%20Experience&channelName=Azure%20CLI&createdTime=1593404934668

Added an cli-extension issue here: https://github.com/Azure/azure-cli-extensions/issues/1953

**Comment by changlong-liu** [comment]
close since tracked in cli-extension issue.
