### ISSUE TITLE
Flake8 Style Check Failure of Generated Code: _params

### ISSUE THREAD

**Issue by LianwMS** [Azure/autorest.az#443]
d:\git\azure-cli-extensions\src\testserver\azext_testserver\generated\_params.py:15:1: E303 too many blank lines (3)
d:\git\azure-cli-extensions\src\testserver\azext_testserver\generated\_params.py:32:63: F841 local variable 'c' is assigned to but never used
1     E303 too many blank lines (3)
1     F841 local variable 'c' is assigned to but never used

**Comment by RodgeFu** [comment]
@LianwMS ,  please provide the swagger file for further investigation. thx

**Comment by LianwMS** [comment]
Merge and close
