### ISSUE TITLE
DF onboard: generated test should not use argument value in test func definition directly

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#448]
I don't think we should use the argument value in the example when generate the test function implementation. Which is hard to customize when the argument is going to be changed.
https://github.com/Azure/azure-cli-extensions/pull/1321/files#diff-d70a473b9ad1c7c1169fb89d7eb055edR216-R226
Instead, I think the argument value should only be defined before call the scenario.

**Comment by changlong-liu** [comment]
have a story to customize example parameters with directive.
