### ISSUE TITLE
resource_group should be resource_group_name

### ISSUE THREAD

**Issue by MyronFanQiu** [Azure/autorest.az#47]
```
def create_powerbiembedded_workspace_collection(cmd, client,
                                                resource_group,
```
should be 
```
def create_powerbiembedded_workspace_collection(cmd, client,
                                                resource_group_name,
```

**Comment by RodgeFu** [comment]
is that a CLI convension?

**Comment by MyronFanQiu** [comment]
yes. It's a CLI convension. And it's also related with this issue. https://github.com/Azure/autorest.az/issues/46 if you want to get location of resource group as the default location. CLI will use `resource_group_name` to get the location.
