### ISSUE TITLE
[CLI] Parameter naming

### ISSUE THREAD

**Issue by qwordy** [Azure/autorest.az#517]
I am generating Swiftlet CLI commands with autorest. Some advice on parameter naming. Usually, the name of resource has parameter name "--name" and it supports shorthand form "-n".
```
c.argument('vm_name', type=str, help='The name of the virtual machine.', id_part='name')
```

**Comment by qiaozha** [comment]
close this one as explained offline. Thanks

**Comment by qwordy** [comment]
I suggest explain here. Open source spirit. Share knowledge with more people.
