### ISSUE TITLE
Support configuring is_preview/is_experimental in different levels

### ISSUE THREAD

**Issue by jsntcy** [Azure/autorest.az#536]
As a CodeGen user, I want to configure is_preview/is_experimental in different levels (command group, command, argument), but not just extension level (current support).

`self.command_group('xxx', is_experimental=True)`
`g.command('xxx', is_experimental=True)`
`c.argument('xxx', is_experimental=True)`

**Comment by t-yuminghe** [comment]
@jsntcy This feature is already supported, you can see the detailed usage document in faq.md which is in the doc folder.

**Comment by t-yuminghe** [comment]
@jsntcy This feature is already supported, you can see the detailed usage document in faq.md which is in the doc folder.
Thanks.

**Comment by LianwMS** [comment]
Merged and closed
