### ISSUE TITLE
Expose key of a named collection as a parameter

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#58]
In the `create_or_update` operation of Blueprint, [resourceGroups](https://github.com/Azure/azure-rest-api-specs/blob/2f48d306ba63a7ea3c19bd122a274dc465a84e4c/specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/blueprintDefinition.json#L847) is added as a [named collection](https://github.com/Azure/azure-rest-api-specs/blob/2f48d306ba63a7ea3c19bd122a274dc465a84e4c/specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/blueprintDefinition.json#L1200) which will be mapped as a dictionary in python. Its key would be used to get/update/delete a resource group artifact in the blueprint. 

In Azure Portal, this key is not exposed and will be autogenerated as 'ResourceGroup', 'ResourceGroup2' e.t.c. When users operate on the created resource group artifact on GUI, the underlying key will be used when sending requests to the service. 

In Azure CLI, we need to let users be able to name this key so they can later use this key to operate the created resource group. So we want to expose the key parameter.

I'm not sure how common named collection is used in swagger. This could be of low priority if it's not a common use.

**Comment by qiaozha** [comment]
close as codegen already support this with json.
