### ISSUE TITLE
Override global configuration of extension-mode is not working

### ISSUE THREAD

**Issue by haroldrandom** [Azure/autorest.az#597]
### Reproduce Process

I have a global configure to make every command group is _stable_ by default,
```
``` yaml
# Migrated from Powershell's readme

extension-mode: stable
```
and will mark some specific command group as _preview_ status.

Here is my scenario. The command group of `billing invoice` is stable as before, but the sub-command group `billing invoice section` is preview because it's added recently.

However, an override like that doesn't work.
```
- where:
    operationGroup: billingAccounts
  set:
    groupExtensionMode: preview
```

the `billing invoice section` is still stable without _preview_ sign.

### Workaround 
override it in manual/_params.py
```Python
    with self.command_group("billing invoice section",
                            billing_invoice_section,
                            client_factory=cf_invoice_section,
                            is_preview=True):
        pass  # inherit commands from generated/ and add is_preview=True
```

Here is my config https://github.com/Azure/azure-rest-api-specs/blob/master/specification/billing/resource-manager/readme.az.md. 
And I have already overwritten it in manual/commands.py

**Comment by changlong-liu** [comment]
fixed in latest private release
