### ISSUE TITLE
Deplicated test function if example name in swagger is duplicated too

### ISSUE THREAD

**Issue by haroldrandom** [Azure/autorest.az#599]
The example in the swagger for this is duplicated before the fix. https://github.com/Azure/azure-rest-api-specs/pull/11261/files. And Resulting in this, the test function name is duplicated too.

![image](https://user-images.githubusercontent.com/14357159/96977325-81403300-154f-11eb-979a-8f57ab80306d.png)

I don't know whether it's good to add a CI checks or validation to restrict this behavior.

I am open to this.

**Comment by changlong-liu** [comment]
because there are two example with same name under same http operation. should be fix in swagger.

**Comment by haroldrandom** [comment]
> because there are two example with same name under same http operation. should be fix in swagger.

Should add a check in CI?

**Comment by changlong-liu** [comment]
Hi @haroldrandom , in swagger CI as a linter rule? I think we can propose it

**Comment by changlong-liu** [comment]
fixed, and proposed prohibit duplicated example names
