### ISSUE TITLE
Improvement: support customized vendored sdk path

### ISSUE THREAD

**Issue by evelyn-ys** [Azure/autorest.az#609]
For now, the python-sdk-output-folder should be `$(az-output-folder)/azext_X/vendored_sdks/Y`, which Y matches with namespaces.split(".")[-1].
For example, if I have namespace `azure.mgmt.storage`, and I want to generate the cli code in cli extension module `storage-preview`, then the python-sdk-output-folder can only be `$(az-output-folder)/azext_storage_preview/vendored_sdks/storage`.

However, storage module needs several sdks including data plane and management plane. I'll need customized vendored sdk path.

**Comment by changlong-liu** [comment]
supported in latest private version
