### ISSUE TITLE
upgrade azure-mgmt-core so that latest codegen can work 

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#614]
The latest autorest.python 5.4.0 has upgraded the dependency of azure-mgmt-core to 1.2.1 and azure-cli-core is still using 1.2.0 

And autorest.az has already upgraded to the latest autorest.python 5.4.0.

To make it work azure-cli-core need to release a new version with latest azure-mgmt-core.

**Comment by changlong-liu** [comment]
fixed
