### ISSUE TITLE
Able to group show command automatically

### ISSUE THREAD

**Issue by haroldrandom** [Azure/autorest.az#615]
As for `billing role-assignment`, it would be convenient for us to group it together automatically. Otherwise, we have to hide these there methods and override them manually.

![image](https://user-images.githubusercontent.com/14357159/98067668-11a63e00-1e95-11eb-93b5-2d228a72c246.png)

![image](https://user-images.githubusercontent.com/14357159/98067744-369ab100-1e95-11eb-8c8f-ab061f3abf10.png)

![image](https://user-images.githubusercontent.com/14357159/98067748-38fd0b00-1e95-11eb-8afa-f8cbbdcbee49.png)

**Comment by changlong-liu** [comment]
supported
