### ISSUE TITLE
Remove duplicated command group name

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#620]
Could we make sure no such duplicated command group generated? For example, when I name the extension as `diskpool` and there is operation group `DiskPool_Operations`, `az diskpool disk-pool` will be generated as below. But the expected design is `az disk-pool` with CRUD and `az disk-pool iscsi-target` command group.

![image](https://user-images.githubusercontent.com/49508232/98514930-38a1ad00-22a5-11eb-8e0f-ceb7109c1380.png)

expected design: 
![image](https://user-images.githubusercontent.com/49508232/98522784-0fd2e500-22b0-11eb-9cc4-c474d7720c73.png)

Note: I could get expected design with directive settings.

**Comment by changlong-liu** [comment]
fix since PR merged
