### ISSUE TITLE
Refine help message for command group

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#621]
### Description
disk_pool is an operation group.
The generated command group help message have "-" as shown below:
![image](https://user-images.githubusercontent.com/49508232/98761497-82f36d00-2410-11eb-9746-6679f2b0fdeb.png)

what we expect is as shown here:
![image](https://user-images.githubusercontent.com/49508232/98762105-e0d48480-2411-11eb-91ec-9b8daf5cf707.png)

### Solution
Refine it in manual folder.
### Expected solution
1. Try to make swagger have description for operation group.
2. Could try to add friendly description for command group not just command group name. For example,
- removing `-`
- add `manage` as the first verb

**Comment by changlong-liu** [comment]
close since PR merged
