### ISSUE TITLE
Make --location not required

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#622]
#### Description
--location is required in CodeGen generated command with get location from resource group. In this way, it should not be required.
![image](https://user-images.githubusercontent.com/49508232/98763352-cf40ac00-2414-11eb-87a3-d8909bdc9ddb.png)

expected:
![image](https://user-images.githubusercontent.com/49508232/98764034-e9c75500-2415-11eb-979e-f3aecaa884ee.png)

#### Solution
add required=False in location in manual
```
    with self.argument_context('disk-pool') as c:
        c.argument('location', arg_type=get_location_type(self.cli_ctx), required=False,
                   validator=get_default_location_from_resource_group)
```

**Comment by changlong-liu** [comment]
close since PR merged
