### ISSUE TITLE
Use `nargs='+'` for array list

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#625]
#### Description

The generated parameter for array is using `nargs='*'` as shown below:
```
        c.argument('availability_zones', nargs='*', help='Logical zone for DiskPool resource.')
        c.argument('disks', action=AddDisks, nargs='*', help='List of Azure managed disks to attach to a DiskPool')
```

Expected behavior:

could we use `nargs='+'` for array list? Here is an example in CLI code:
https://github.com/Azure/azure-cli/blob/8de0fc1accf0fa1c503ecf408e06d69cc7a8f2e2/src/azure-cli/azure/cli/command_modules/network/_params.py#L253

reference:
'+'. Just like '*', all command-line args present are gathered into a list. Additionally, an error message will be generated if there wasn’t at least one command-line argument present. For example:

**Comment by changlong-liu** [comment]
close since PR merged
