### ISSUE TITLE
Keyword match for duplicated test examples in CreateOrUpdate api

### ISSUE THREAD

**Issue by evelyn-ys** [Azure/autorest.az#630]
For now, to distinguish create example and update example, the `x-ms-examples` name should be `SomePrefix_create`/`SomePrefix_update`.
Is it possible to add keyword match rule in codeGen to distinguish the example below?
![image](https://user-images.githubusercontent.com/10227683/99040446-1ae58800-25c4-11eb-81c9-6ed2fc09be79.png)

**Comment by changlong-liu** [comment]
close since PR merged
