### ISSUE TITLE
"--sdk-no-flatten  --compatible-level=track2" generate flatten and no-flatten SDKs 

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.az#650]
azure-rest-api-specs repo [link](https://github.com/kairu-ms/azure-rest-api-specs/tree/f90126e44297913610444eff1a4193b9b02d6eab)

Codegen Command:

```shell
autorest --az --use=https://github.com/Azure/autorest.az/releases/download/1.6.2-b.20201120.1/autorest-az-1.6.2.tgz --azure-cli-extension-folder=./azure-cli-extensions --generation-mode=full --target-mode=extension --generate-sdk=yes --sdk-no-flatten --compatible-level=track2 ./azure-rest-api-specs/specification/monitor/resource-manager/readme.md
```

Flatten SDK operations:

- https://github.com/kairu-ms/azure-cli-extensions/blob/6d4721852cc90b95b8a0e70db3a82d87e413a871/src/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rule_association_operations.py
- https://github.com/kairu-ms/azure-cli-extensions/blob/6d4721852cc90b95b8a0e70db3a82d87e413a871/src/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rule_operations.py

No-flatten SDK operations:

- https://github.com/kairu-ms/azure-cli-extensions/blob/6d4721852cc90b95b8a0e70db3a82d87e413a871/src/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rule_associations_operations.py
- https://github.com/kairu-ms/azure-cli-extensions/blob/6d4721852cc90b95b8a0e70db3a82d87e413a871/src/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rules_operations.py

**Comment by changlong-liu** [comment]
released in private build
