### ISSUE TITLE
flattened parameters has schema prefix while flattened sdk miss this prefix. That cause problem in cli parameters parsing

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.az#652]
azure-rest-api-specs repo [link](https://github.com/kairu-ms/azure-rest-api-specs/tree/f7dac59d684ddedc2fc3d8a7bd6f161761d5cd8a)

[Generated parameters with schema prefix 'destinations_'](https://github.com/kairu-ms/azure-cli-extensions/blob/14238a86db9c2a292385e87b68b95df119416fa9/src/monitor-control-service/azext_amcs/generated/_params.py#L70-L73)

```py
        c.argument('destinations_log_analytics', action=AddDestinationsLogAnalytics, nargs='+', help='List of Log '
                   'Analytics destinations.')
        c.argument('destinations_azure_monitor_metrics', action=AddDestinationsAzureMonitorMetrics, nargs='+',
                   help='Azure Monitor Metrics destination.')
```

[flattened sdk miss prefix 'destinations_'](https://github.com/kairu-ms/azure-cli-extensions/blob/14238a86db9c2a292385e87b68b95df119416fa9/src/monitor-control-service/azext_amcs/vendored_sdks/amcs/operations/_data_collection_rule_operations.py#L263-L264)

```py
def create(
        self,
        log_analytics=None,  # type: Optional[List["models.LogAnalyticsDestination"]]
        azure_monitor_metrics=None,  # type: Optional["models.AzureMonitorMetricsDestination"]
        **kwargs  # type: Any
    ):
```

That will cause redundant arguments in parameters parsing when we using 'generic_update_command'

![image](https://user-images.githubusercontent.com/69238381/100313136-ec69a300-2fee-11eb-87d8-be81ae21cb72.png)

**Comment by changlong-liu** [comment]
merged
