### ISSUE TITLE
Name formatting options for flattened parameter

### ISSUE THREAD

**Issue by evelyn-ys** [Azure/autorest.az#658]
This comes from such scenario:
Parameter name could be too long and nagging. For example, To flatten `contactInformation` which has four properties: `contactPerson`, `companyName`, `phone`, `emailList`, these properties will be `--contact-information-contact-person`, `--contact-information-company-name`, `--contact-information-phone` and `--contact-information-email-list` after flattening
![image](https://user-images.githubusercontent.com/10227683/100564800-fc3dfb80-32fc-11eb-8cdc-11d0be40db12.png)
The prefix is somehow **redundant**

However, in some cases the prefix is **necessary**. For example, To flatten `sku` with `name` and `tier` properties, it should be `sku-name` and `sku-tier` after falttening.

So can the name formatting be optional for flattened parameter? We can choose to add prefix or not on demand.

**Comment by changlong-liu** [comment]
close since merged
