### ISSUE TITLE
datafactory --sdk-no-flatten issues

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#672]
1. Undefined argument 
![image](https://user-images.githubusercontent.com/55688292/101309348-2d7f7400-3887-11eb-8d66-d3b9f6aa040a.png)
2. poly simple scenarios error 
![image](https://user-images.githubusercontent.com/55688292/101309446-66b7e400-3887-11eb-98ef-c6fe2ee865e5.png)

**Comment by changlong-liu** [comment]
merged
