### ISSUE TITLE
exception is not raised immediately in test scenrios

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#674]
For test scenarios, typically the following command will depend on the result of previous command.
So in my case, when the first command fails, the following steps will fail, too. For such work flow, I will expect the exception is raised  immediately because cached exceptions will be not meaningful.

In addition, with cached exceptions, the error log is too long and is hard to find the first error info.
Could we also expose the line that error happens in test step?

Current error log:
![image](https://user-images.githubusercontent.com/49508232/101322564-36ca0a00-38a2-11eb-8081-8c3c30a1a106.png)

**Comment by changlong-liu** [comment]
merged
