### ISSUE TITLE
Feedback of documentation

### ISSUE THREAD

**Issue by qwordy** [Azure/autorest.az#685]
1. Segmentation
Documentations locate in various repositories and paths. We need one overview documentation and provide links to other documentations.
I received these links when I consulted usage.
https://raw.githubusercontent.com/Azure/autorest.az/master/src/test/scenarios/kusto/configuration/readme.az.md
https://github.com/Azure/autorest.clicommon/blob/master/doc/cli-directive.md
https://github.com/evelyn-ys/azure-rest-api-specs/blob/localUserCodeGen/specification/storage/resource-manager/readme.az.md
https://github.com/Azure/autorest.az/blob/master/doc/faq.md#how-to-support-configuring-is_previewis_experimental-in-different-levels
https://github.com/Azure/autorest.az/blob/master/doc/how-to-generate-with-different-options.md#--target-mode-option

2. Tutorial
Tutorials will be helpful for a new user. It is a step-by-step guidance of typical use cases.

3. Repository's homepage
The readme file is misused. It is a convention that README.md in root folder is an introduction of this project. However, this file in this repository is used as a configuration file now.

**Comment by changlong-liu** [comment]
merged
