### ISSUE TITLE
Wrong extension name in record.md

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#708]
The extension name is `diskpool` and command group name is `az disk-pool` after renaming in readme, not `az diskpool`.
![image](https://user-images.githubusercontent.com/49508232/104142781-f5c09a80-53f7-11eb-841f-7b22cbbe58ae.png)

**Comment by changlong-liu** [comment]
@Juliehzl , would you confirm whether still be a issue?

**Comment by changlong-liu** [comment]
Hi, @Juliehzl , close for now, contact us if still have issue.
