### ISSUE TITLE
Generate changelog for command interface and tooling info

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#712]
1. Add autorest.info and swagger file info for each generation		
- Readme from remote with commit id to fix the version
- autorest info
❯ autorest --az --use=https://github.com/Azure/autorest.az/releases/download/1.6.2-b.20201119.3/autorest-az-1.6.2.tgz --sdk-no-flatten E:\Microsoft\Swagger\azure-rest-api-specs-pr\specification\storagepool\resource-manager\readme.md --azure-cli-extension-folder=./
AutoRest code generation utility [cli version: 3.0.6247; node: v14.15.1, max-memory: 4096 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
		 Loading AutoRest core      'C:\Users\zuh\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
		 Loading AutoRest extension '@autorest/az' (https://github.com/Azure/autorest.az/releases/download/1.6.2-b.20201119.3/autorest-az-1.6.2.tgz->1.6.2)
		 Loading AutoRest extension '@autorest/python' (5.4.0->5.4.0)
		 Loading AutoRest extension '@autorest/clicommon' (0.5.7->0.5.7)
 Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)

2. Detect diff of command interface with last generation. For example:
- New command for which group
- New parameter for which command
- which parameter name change
- ...

**Comment by changlong-liu** [comment]
item 1: will add more data in gen.zip
item 2 should be out of codegen scope.

**Comment by changlong-liu** [comment]
close since:
1. git info is added in gen.zip
2. change log will use Rukai's tool
