### ISSUE TITLE
[Bug] Missing quotation marks around 'core' inside readme.az setup instructions

### ISSUE THREAD

**Issue by greenms** [Azure/autorest.az#744]
Link to page with issue: https://github.com/Azure/autorest.az/blob/master/doc/how-to-author-readme-file.md

These two lines need to be updated:

OLD:     ``` yaml $(az) && $(target-mode) != core
             ```
NEW:     ``` yaml $(az) && $(target-mode) != 'core'
             ```

OLD:     ``` yaml $(az) && $(target-mode) == core
             ```
NEW:     ``` yaml $(az) && $(target-mode) == 'core'
             ```

**Comment by changlong-liu** [comment]
merged
