### ISSUE TITLE
ImportError are passed when it's not caused by manual files not exist

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.az#762]
Machine Learning Team is working on a new extension and they did a lot of manual code to use their own SDK. They have some import errors when using their own SDKs, but the current code in `custom.py` below will just ignore any `ImportError` and CLI will eventually throw an error like `ModuleNotFoundError: No module named 'azure.ml'`. This cost them a lot of effort finding the real issue.

It may be a good idea to only pass `ImportError` for the `.manual.custom` part.

```
from .generated.custom import *  # noqa: F403
try:
    from .manual.custom import *  # noqa: F403
except ImportError:
    pass
```

**Comment by qiaozha** [comment]
close it as supported in master branch. Please use latest private release to make it work.
