### ISSUE TITLE
[datashare] incorrect original operation group name after using directive to move the operation group

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#770]
![image](https://user-images.githubusercontent.com/55688292/110268534-c2b41500-7ffc-11eb-81fe-655f247f82cb.png)

In such case, the python codemodel of consumer share-subscription doesn't have an operation named list, we need to record the original operation group name while moving operation from one group to another. And call that original operation group while call python SDK.

**Comment by changlong-liu** [comment]
pr merged
