### ISSUE TITLE
Doc index from CLI command perspective

### ISSUE THREAD

**Issue by houk-ms** [Azure/autorest.az#771]
### Why do you need this feature?

Expect to have a doc index from CLI command perspective so that we can easily find how to customize the readme.az. This would help us learn how to config readme.az more efficiently.

### Is your feature request related to a problem? Please describe.

Problem is it's time-consuming for us to find how to config the readme.az to adjust the command interface.

### Describe the solution you'd like
For reference, use a config index like this https://github.com/houk-ms/autorest.az/blob/master/doc/index.md

### Describe alternatives you've considered
No

### Additional context
No

**Comment by changlong-liu** [comment]
merged
