### ISSUE TITLE
Parameter Type, validate_file_or_dict VS. file_type

### ISSUE THREAD

**Issue by qwordy** [Azure/autorest.az#798]
This is a generated parameter definition.
```
        c.argument('secrets', type=validate_file_or_dict, help='Specifies set of certificates that should be installed '
                   'onto the role instances. Expected value: json-string/@json-file.', arg_group='Os Profile')
```
(1) The help text has a mistake. It should be `json-string/json-file/@json-file`
(2) It is recommended to use `file_type` instead of `validate_file_or_dict`. `file_type` also support direct string. It does not require a dict format. It allows more flexibility. `Expected value: json-string/@json-file`

**Comment by changlong-liu** [comment]
will communicate offline

**Comment by lirenhe** [comment]
Fixed
