### ISSUE TITLE
Cannot config `exception_handler` property for commands

### ISSUE THREAD

**Issue by kairu-ms** [Azure/autorest.az#801]
**Why do you need this feature?**

We need to customize exception_handler of command.

**Is your feature request related to a problem? Please describe.**

Cannot config exception_handler property like this
```python
g.custom_command('validate', 'validate_arm_template', exception_handler=handle_template_based_exception)
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jsntcy** [comment]
https://github.com/Azure/autorest.az/issues/789

**Comment by qiaozha** [comment]
find the solution here https://github.com/Azure/autorest.az/issues/789#issuecomment-809187026

**Comment by changlong-liu** [comment]
merged
