### ISSUE TITLE
[DataProtection] Wrong argument name in example generation

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#802]
![image](https://user-images.githubusercontent.com/55688292/112937975-50e26d80-915b-11eb-941d-dbd7ddd0f81a.png)

This should be a polymorphism simple scenario. 

check out this branch to repro https://github.com/Azure/azure-rest-api-specs/tree/cli-config-for-dataprotection

**Comment by changlong-liu** [comment]
merged
