### ISSUE TITLE
[marketplaceordering] test generation duplicate parameter in test and example generation

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.az#828]
![image](https://user-images.githubusercontent.com/55688292/115145734-a38db600-a085-11eb-9166-ff6d1504ed32.png)

This case they have put planId, publisher_id, offer_id parameter both in path and in body 
![image](https://user-images.githubusercontent.com/55688292/115145803-08491080-a086-11eb-9413-ea42af7c4d27.png)

To repo use this PR branch 
https://github.com/Azure/azure-rest-api-specs/pull/12484

**Comment by changlong-liu** [comment]
PR merged to master
