### ISSUE TITLE
The autorest.python can't be installed.

### ISSUE THREAD

**Issue by changlong-liu** [Azure/autorest.az#85]
## Issue
While there are below configurations in README.md, the autorest.python plugin is expected to be installed while loading autorest.az.
```
use-extension:
  "@autorest/clicommon": "latest"
  "@autorest/python": "https://github.com/Azure/autorest.python/releases/download/v5.0.0_20200123/autorest-python-5.0.0-20200123.tgz" 
```

 But the installation is failed as below.
![image](https://user-images.githubusercontent.com/59815250/73705375-c2c64f00-4730-11ea-8f2e-297186d473dd.png)

As a work round: commenting out the use-extension for @autorest/python, and using the local autorest.python is OK.
![image](https://user-images.githubusercontent.com/59815250/73705647-7b8c8e00-4731-11ea-8c4d-ecbcd47d2bd2.png)

## Environment
My OS: Ubuntu 18.04
My python pip freeze: 
[my_pip_freeze.txt](https://github.com/Azure/autorest.az/files/4151005/my_pip_freeze.txt)
Node version: v12.14.1

**Comment by LianwMS** [comment]
NA for now
