### ISSUE TITLE
Log the importErrors instead of silently passing

### ISSUE THREAD

**Issue by Mossaka** [Azure/autorest.az#878]
Please log the errors instead of silently passing them in `__init__.py`, `action.py` and `custom.py` because it is creating a log headache to debug issues with loading the extension wheels. 

For example, in `__init__.py`, we are see
```python
def load_command_table(self, args):
        from azext_mlv2.generated.commands import load_command_table

        load_command_table(self, args)
        try:
            from azext_mlv2.manual.commands import load_command_table as load_command_table_manual

            load_command_table_manual(self, args)
        except ImportError:
            pass
        return self.command_table
```

The issue is on this line `except ImportError:`: without logging/printing out the error messages, it is very hard for us to debug what went wrong with the imports. It easily took us one dev's day to debug it because all we are seeing from azure cli `--debug` is 
```
cli.azure.cli.core.azclierror: 'ml' is misspelled or not recognized by the system.
az_command_data_logger: 'ml' is misspelled or not recognized by the system.
```

If you could change it to
```python
except ImportError as e:
    logger.debug(e)
```
this will make debugging experience much easier!

The same suggestion applies to `action.py` and `custom.py`
```python
from .generated.action import *  # noqa: F403

try:
    from .manual.action import *  # noqa: F403
except ImportError as e:
    logger.debug(e)
```

**Comment by Mossaka** [comment]
@kairu-ms gently ping

**Comment by kairu-ms** [comment]
@Mossaka it has been fixed in pre release version. 
Please add argument `--use=https://github.com/Azure/autorest.az/releases/download/1.7.3-b.20210818.1/autorest-az-1.7.3.tgz` and have a try. Thanks.
