### ISSUE TITLE
Automatically  add vendored sdk folder and change import

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#94]
It will be better to add generated SDK into vendored sdk folder and change import part.
Currently we have to add the SDK into target folder manually and change import part. For example,

`from src.powerbidedicated.azext_powerbidedicated.vendored_sdks import models`
changes to
`from .. import models`

**Comment by RodgeFu** [comment]
We will have this in the new version of CodeGen which is coming soon.
