### ISSUE TITLE
Why do we use resource_group rather than resource_group_name?

### ISSUE THREAD

**Issue by Juliehzl** [Azure/autorest.az#96]
Because I want to use cli build-in function get_default_location_from_resource_group() as I have mention in https://github.com/Azure/autorest.az/issues/43#issuecomment-586180037.

But the function will utilize the resource_group_name in namespace. May I know why we use resource_group in custom_function not resource_group_name as what is required in SDK?

**Comment by qiaozha** [comment]
https://github.com/Azure/autorest.az/issues/47 this is already been fixed in the latest code. May I know what autorest command are you using now?
